---
- name: Check if kube controller manager binary exists at the required location
  stat:
    path: "{{ kubernetes_binaries_directory }}/kube-controller-manager"
  register: kube_controller_manager_binary_exists

- name: debug
  debug:
    var=kube_controller_manager_binary_exists

- name: Check if kube controller manager binary version matches with the required version
  shell: kube-controller-manager --version | awk '{print $2}'
  register: kube_controller_manager_version_check
  when: kube_controller_manager_binary_exists.stat.exists == True

- name: debug
  debug:
    var=kube_controller_manager_version_check


- name: Download the kube controller manager binary file
  get_url:
    url: "{{ kube_controller_manager_download_url }}"
    dest: "{{ kubernetes_download_directory }}"
  when: kube_controller_manager_binary_exists.stat.exists == False

- name: Move the kube controller manager binary to PATH variable locations
  copy:
    src: "{{ kubernetes_download_directory }}/kube-controller-manager"
    dest: "{{ kubernetes_binaries_directory }}"
    owner: root
    group: root
    mode: "a+x"
    remote_src: yes
  when: kube_controller_manager_binary_exists.stat.exists == False

- name: Creating the Private Key for the kube-controller-manager
  openssl_privatekey:
   path: "{{ kubernetes_conf_directory }}/kube-controller-manager.key"
   type: "RSA"
   size: 2048

- name: Creating the Ceritificate Signing Request for the created Private Key
  openssl_csr:
    path: "{{ kubernetes_conf_directory }}/kube-controller-manager.csr"
    privatekey_path: "{{ kubernetes_conf_directory }}/kube-controller-manager.key"
    common_name: "system:kube-controller-manager"
  
- name: Generate an OpenSSL certificate signed with our own CA certificate
  openssl_certificate:
    path: "{{ kubernetes_conf_directory }}/kube-controller-manager.crt"
    csr_path: "{{ kubernetes_conf_directory }}/kube-controller-manager.csr"
    ownca_path: "{{ kubernetes_conf_directory }}/ca.crt"
    ownca_privatekey_path: "{{ kubernetes_conf_directory }}/ca.key"
    provider: ownca


- name: Generating the Kube config file for kube-controller-manager - 1
  shell: kubectl config set-cluster "{{ kuberentes_cluster_name }}" --certificate-authority="{{ kubernetes_conf_directory }}/ca.crt" --embed-certs=true --server=https://127.0.0.1:6443 --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: "{{ kubernetes_conf_directory }}"
  register: kube_config_generate_1

- name: debug kube config generate 1
  debug:
    var=kube_config_generate_1

- name: Generating the kube config file for kube-controller-manager - 2
  shell: kubectl config set-credentials system:kube-controller-manager --client-certificate="{{ kubernetes_conf_directory }}/kube-controller-manager.crt" --client-key="{{ kubernetes_conf_directory }}/kube-controller-manager.key" --embed-certs=true --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: "{{ kubernetes_conf_directory }}"
  register: kube_config_generate_2

- name: debug kube config generate 2
  debug:
    var=kube_config_generate_2

- name: Generating the kube config file for kube-controller-manager - 3
  shell: kubectl config set-context default --cluster="{{ kuberentes_cluster_name }}" --user=system:kube-controller-manager --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: "{{ kubernetes_conf_directory }}"
  register: kube_config_generate_3

- name: debug kube config generate 3
  debug:
    var=kube_config_generate_3

- name: Generatign the kube config file for kube-controller-manager - 4
  shell: kubectl config use-context default --kubeconfig=kube-controller-manager.kubeconfig
  args:
    chdir: "{{ kubernetes_conf_directory }}"
  register: kube_config_generate_4

- name: debug kube config generate 4
  debug:
    var=kube_config_generate_4

- name: Creating the kube controller manager systemd service unit file
  template:
    src: "kube-controller-manager.service.j2"
    dest: "/etc/systemd/system/kube-controller-manager.service"
    owner: root
    group: root
  notify: 
    - systemd reload

- name: Enabling and start the kube controller manager service
  systemd:
    name: kube-controller-manager
    state: started
    enabled: true